version: '3'

services:
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
  awscli:
    image: public.ecr.aws/aws-cli/aws-cli
    depends_on:
      - dynamodb
    environment:
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_ENDPOINT: --endpoint-url=http://dynamodb:8000
    command: dynamodb create-table --table-name feature-toggle --attribute-definitions AttributeName=PK,AttributeType=S AttributeName=SK,AttributeType=S --key-schema AttributeName=PK,KeyType=HASH AttributeName=SK,KeyType=RANGE --billing-mode PAY_PER_REQUEST
  list_tables:
    image: public.ecr.aws/aws-cli/aws-cli
    depends_on:
      - dynamodb
    environment:
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_ENDPOINT: --endpoint-url=http://dynamodb:8000
    command: dynamodb list-tables
